flowchart TD
    Accuracy[Accuracy is a relevant non-functional requirement]
    Accuracy --> DataCorrectness[Data values are correct and not approximations]
    DataCorrectness --> EstimationAlgorithms[Estimation algorithms trade off accuracy for lower complexity]
    EstimationAlgorithms --> HyperLogLog[HyperLogLog for cardinality estimate in Presto]
    EstimationAlgorithms --> CountMinSketch[Count-min sketch for estimating frequencies in stream data]
    CacheStaleness[Cache is stale if data in underlying database is modified]
    CacheStaleness --> RefreshPolicy[Cache may have a refresh policy]
    RefreshPolicy --> |Short| Costly[Short refresh policy is more costly]
    RefreshPolicy --> |Alternative| UpdateOrDelete[Update or delete cache key upon data modification]
    AccuracyConsistency[Accuracy is somewhat related to consistency]
    AccuracyConsistency --> EventuallyConsistent[Eventually consistent systems trade off accuracy for improvements]
    EventuallyConsistent --> InaccurateResults[Results from reads may not include effects of recent writes]
    InaccurateResults --> ReplicasUpdated[Replicas need to be updated with write effects]
    ReplicasUpdated --> |Term used| ConsistencyDiscussion[Use term consistency to discuss situation, not accuracy]
