graph TD;
    Availability --> High_Availability;
    High_Availability --> |Non-functional Requirements| Trade_Offs;
    Trade_Offs --> |CAP Theorem| Strong_Consistency;
    Trade_Offs --> |CAP Theorem| Low_Latency;
    Strong_Consistency --> Asynchronous_Communication;
    Low_Latency --> Asynchronous_Communication;
    Asynchronous_Communication --> |Event Sourcing| Logging;
    Asynchronous_Communication --> |Saga| Requests;
    Requests --> Immediate_Processing;
    Immediate_Processing --> Synchronous_Communication;
    Synchronous_Communication --> Immediate_Response;
    Immediate_Response --> Acknowledgment;
    Immediate_Response --> |Data Return Later| Delayed_Response;
    Delayed_Response --> Queue_Request;
    Queue_Request --> Processing;
    Processing --> Notify_User;
    High_Availability --> |Caching Service| Trade_Off;
    Trade_Off --> Lower_Latency;
    Availability --> Incident_Metrics;
    Incident_Metrics --> |MTTR| Mean_Time_to_Recovery;
    Incident_Metrics --> |MTBF| Mean_Time_Between_Failures;
