sequenceDiagram
    participant App as Application
    participant Cache as Cache
    participant DB as Database

    App ->> Cache: Read Request
    alt Cache Hit
        Cache -->> App: Return Data
    else Cache Miss
        Cache ->> DB: Read Request
        DB -->> Cache: Data
        Cache ->> App: Data
    end

    note over Cache: Lazy Load: Data is loaded only when first read

    note right of Cache: Read-through is best for read-heavy loads

    note left of Cache: In read-through,the cache may contact the database if necessary.

    note left of Cache: Unlike cache-aside,read-through cannot group multiple requests into a single cache value.
