sequenceDiagram
    participant App as Application
    participant Cache as Cache
    participant DB as Database

    App ->> Cache: Read Request
    alt Cache Hit
        Cache -->> App: Return Data
    else Cache Miss
        Cache ->> DB: Read Request
        DB -->> Cache: Data
        Cache ->> App: Data
    end

    note over Cache: Lazy Load\nData is loaded\nonly when\nfirst read

    note right of Cache: Read-through\nis best for\nread-heavy loads

    note left of Cache: In read-through,\nthe cache may\ncontact the\ndatabase\nif necessary.

    note left of Cache: Unlike cache-aside,\nread-through\ncannot group\nmultiple\nrequests\ninto a\nsingle cache\nvalue.
