graph LR
    A(Edge Cases and New Constraints) --> B[Functional Requirements]
    A --> C[Scalability and Performance]
    A --> D[Latency and Throughput]
    A --> E[Availability and Fault-Tolerance]
    A --> F[Cost]

    B --> B1[Customizable Payment System]
    B --> B2[Extending Search Service]
    B --> B3[Handling Room Changes]
    B --> B4[Adding Social Networking Features]

    C --> C1[Handling One Million Followers]
    C --> C2[Auditing Sales Data]

    D --> D1[P99 Message Delivery Time]
    D --> D2[Supporting Live Streaming]

    E --> E1[High Availability Cache]
    E --> E2[High-Frequency Trading]
    E --> E3[Preventing Component Failures]

    F --> F1[Trade-offs for Lower Costs]
    F --> F2[Graceful Service Decommissioning]
    F --> F3[Portability Considerations]
